### ISSUE TITLE
alternative download mirrors

### ISSUE THREAD

**Issue by sreich** [aviaryan/Clipjump#100]
could you please make this available somewhere else as well, to download the binaries? sourceforge is very much not reliable for a while now, and really risky. also companies are actually blocking it because of this.

github allows release downloads/uploads as well, so i think that is the better way forward.

**Comment by aviaryan** [comment]
I will switch to GitHub Releases in the next version.

**Comment by aviaryan** [comment]
Downloads hosted on github from v12.5

**Comment by vanwaard** [comment]
Avi where can I download version 12.5

 

Fred

 

Van: Avi Aryan [mailto:notifications@github.com] 
Verzonden: donderdag 14 april 2016 19:15
Aan: aviaryan/Clipjump
Onderwerp: Re: [aviaryan/Clipjump] alternative download mirrors (#100)

 

Downloads hosted on github from v12.5

**Comment by aviaryan** [comment]
@vanwaard You can get the download link from main site http://bit.ly/clipjump . Isn't that link working ?
Downloads are hosted on github releases. https://github.com/aviaryan/Clipjump/releases

**Comment by sreich** [comment]
It is...  But i should note the auto updater is still broken for those who have source Forge blocked where they work, because it isn't trusted.

**Comment by aviaryan** [comment]
Oh yes. I almost forgot. As the version.txt, the file with latest version information is hosted on sourceforge so auto updating will fail for some users. I will move the file to github in the next version.

**Comment by aviaryan** [comment]
@sreich Are you able to open http://clipjump.sourceforge.net site or not ?

**Comment by sreich** [comment]
I am, I'm even able to click download, but when the download actually triggers, the url/mirror gets blocked, so as to prevent any downloads from source forge

**Comment by aviaryan** [comment]
The download button on the site points to GitHub link, so does the GitHub releases link (https://github.com/aviaryan/Clipjump/releases) open in the browser ? 
If it doesn't, then it's very weird behavior from ISP/browser you are using.

**Comment by sreich** [comment]
Yep. Sigh.. Was another one of Firefox's caching issues (always seems too aggressive). Forcing cache flush (shift click refresh) made the button point to github :)
