### ISSUE TITLE
Version 12.5 doesn't work

### ISSUE THREAD

**Issue by happysurf** [aviaryan/Clipjump#120]
Version 12.5 doesn't work on my XP this morning.
Nothing is captured with Ctrl+C and nothing is pasted with Ctrl+V shortcut.

**Comment by aviaryan** [comment]
Yes. I just got to know about this today, thanks to @Gabr-F ( https://github.com/aviaryan/Clipjump/issues/114#issuecomment-211486167 ).
I will come up with a fix soon.
In the meanwhile, you can manually edit Clipjump.ahk to fix this. You just have to change line 412 and 413. (https://github.com/aviaryan/Clipjump/blob/master/Clipjump.ahk#L412) 
```
	timeDiff := TickCount64() - lastClipboardTime
	lastClipboardTime := TickCount64()
```

Replace TickCount64() by A_TickCount.

**Comment by aviaryan** [comment]
Issue #121

**Comment by happysurf** [comment]
The Clipjump.ahk line changes fix the problem.
Thanks.
