### ISSUE TITLE
save history files to sqlite database

### ISSUE THREAD

**Issue by aviaryan** [aviaryan/Clipjump#13]
History files are simple text files and they can be easily moved to a sqlite database. DB will make working with them efficient and searching in history tool will be more faster.

http://clipjump.sourceforge.net/#comment-1361441153

**Comment by aviaryan** [comment]
https://github.com/aviaryan/Clipjump/tree/db
Development of this feature has been completed in 'db' branch.

**Comment by Gabr-F** [comment]
Congratulations :+1:

So this is only for the History feature, right?

Unfortunately that's a feature I'm not acquainted with (I had not understood it initially and I never felt the need for it). If you write down some test case though I can help you test it, if you want.

Is it supposed to import the old items, by the way? And the channels and the clips inside them ought to be unaffected?

---

As an aside, it would be helpful if you documented the storage system (folders and files used and/or db schema) separately from the source code. For example it would make easier for people to help or debug problems, especially for those unfamiliar with AutoHotKey.

**Comment by aviaryan** [comment]
Yes. This one is the only for the History tool, it will import old history items but leave channels and clips unaffected.

>  (I had not understood it initially and I never felt the need for it).

History is like a record of everything you copy to clipboard. You can choose how many days history you want to store. It stores all the copied items at one place, ordered by time of their creation. 
It comes handy when you have to find something that has been deleted from its channel, like something copied long ago.. Honestly, I too don't use it too often but at times it can be a lifesaver.

**Comment by aviaryan** [comment]
You can try the `db` branch. It should work right out of the box .

**Comment by aviaryan** [comment]
It is merged now.
