### ISSUE TITLE
Run as admin

### ISSUE THREAD

**Issue by danwebkov** [aviaryan/Clipjump#137]
Hello. Cool project. I want say that if you program need admin privilege you can use this code:

if !A_IsAdmin
{
    if A_OSVersion not in WIN_2003,WIN_XP,WIN_2000
    {
        Run *RunAs "%A_ScriptFullPath%" ,, UseErrorLevel
        if !ErrorLevel
            ExitApp
    }
    msgbox, 48, Run Clipjump, Need run as admin.
    ExitApp       
}

This code can run you program as admin without rightclick. For user not usefull every time press right click > run as admin. May be you find this usefull.

**Comment by aviaryan** [comment]
Hey @danzel274 . Thanks for your concern. 
That's a good idea but what we would ideally like here is for the user to decide whether they want to run Clipjump as admin or not. We should not by default force users to run Clipjump as admin.

If user wants to run Clipjump as admin, they can right click on Clipjump.exe, select properties and check the option "Run as administrator". That would run Clipjump.exe as admin automatically everytime.

**Comment by danwebkov** [comment]
Yes indeed it is more correct than my suggestion. Thank you for your tact.
