### ISSUE TITLE
Feature Request: Ability to export all clips in a channel

### ISSUE THREAD

**Issue by gadamiak** [aviaryan/Clipjump#5]
I'm using channels to organize clips concerning a common subject. It would be great to be able to export all clips in the channel to either back them up or share with others/another workstation. This would greatly help in maintaining and using a controlled dictionary I use for issues I resolve most often.

This feature would be useful even more if the exported clip could be edited with external editor. It would be sufficient for me if only editing of only plain text clips would be supported.

**Comment by aviaryan** [comment]
With the current plugin API, exporting (and even importing) clips should be very easy ( use getchstrength, getclipat, emptychannel, addclip etc ). So I am closing this.
