### ISSUE TITLE
Always copy to default clipboard

### ISSUE THREAD

**Issue by danielo515** [aviaryan/Clipjump#61]
It would be helpful to have the option to select a default clipboard. Then all the clips should be saved to that clipboard, no matter which keyboard you have selected. This is useful if you want to have clipboards only for "snippets" and you don't want to care about going back again to the default one.

**Comment by aviaryan** [comment]
How do you want to save to that default channel. I presume you want to have some special shortcut (ctrl+shift+c) that would copy to the default channel instead of current active channel. 
It is possible with Clipjump Custom

**Comment by aviaryan** [comment]
Hey, I just wrote a [plugin for this](https://github.com/aviaryan/clipjump-addons/blob/master/plugins/others/copy2channel.ahk)

Use it with ClipjumpCustom
```
[copy_to_3]
bind = Ctrl+Shift+C
run = API.runPlugin( copy2channel.ahk, 3, 0 )
```

**Comment by danielo515** [comment]
> How do you want to save to that default channel. I presume you want to have some special shortcut (ctrl+shift+c) that would copy to the default channel instead of current active channel. 
It is possible with Clipjump Custom

No, I would like to use it with the normal CTRL+C. I'm not sure If I understood what you are proposing to me. Does your new plugin move what is currently selected on the current channel or does it copy what you just copied to the clipboard?

**Comment by danielo515** [comment]
Hello again.

Your plugin does not seems to work. I just copies to the default clipboard. I'm using the exe version of clipjum, does it matter?

**Comment by aviaryan** [comment]
> Your plugin does not seems to work. I just copies to the default clipboard. I'm using the exe version of clipjump, does it matter?

No.
The 2nd parameter ( run = API.runPlugin( copy2channel.ahk, **3**, 0 ) )  is the channel number that receives the clip when you copy a text with **Ctrl+Shift+C**. So if your active channel is 0 and you copy with Ctrl+Shift+C, then it will go to channel 3 instead of channel 0.
Also the plugin will work only if channel 3 exists... 

> No, I would like to use it with the normal CTRL+C. 

Then how will the program get the logic which clip to move in the default channel and which one to keep in the active channel.

**Comment by danielo515** [comment]
> Then how will the program get the logic which clip to move in the default channel and which one to keep in the active channel.

Sorry, if this is a question I did not get it.

**Comment by danielo515** [comment]
Hello,

> Also the plugin will work only if channel 3 exists...

Additionally to this limitation you have to add that it does not work neither if the destination channel is protected.

**Comment by aviaryan** [comment]
> Additionally to this limitation you have to add that it does not work neither if the destination channel is protected.

I will fix that.. Thanks, didn't notice it.

> Also the plugin will work only if channel 3 exists...

You can't call this a limitation.

**Comment by danielo515** [comment]
Hello @aviaryan ,

I'm trying to write the plugin we were talking about and I'm using your copy2channel plugin as a guide. But there are some things I don't understand that maybe you can explain to me:


```
plugin_copy2channel(zChannel, zWhat){
	if !zWhat
		zSend := "^{vk43}"
	else zSend := "^{vk58}"
```
What are those values? seems like key definitions but I can't understand what are they used for
```
	zoc := CN.NG
	znc := channel_find(zChannel)
```
Correct me if I'm wrong but I thing those are original channel (zoc) and destination channel (znc)

```
	changeChannel(znc)
	ONCLIPBOARD := 3 ; any other positive number other than 1
	Send, % zSend
```
What is this used for? You move to the destination channel and then you set a variable (that I can't understand why) and you send that... keystrokes? Maybe you just copy the content of the clipboard to the selected channel?

```
	while ( ONCLIPBOARD != 1 )
		sleep 100
		
	sleep 500
	changeChannel(zoc)
}
```

Here you wait until ONCLIPBOARD changes, (again, I don't know why) and then you goes back again to the original channel.

Another question not related to your code is: How can I check what is currently on the clipboard in order to run a regular expression check against it? I think I can use getClipAt(0,1,1) but I'm not sure.

Thank you very much.
