### ISSUE TITLE
Delete complet index of a channel

### ISSUE THREAD

**Issue by vanwaard** [aviaryan/Clipjump#63]
Avi is it possible that you can maken it so that the index of a channel can delete complety and not one by one

**Comment by aviaryan** [comment]
Select a channel in Channel organizer, then select Delete and choose No option
![clipjumpchempty](https://cloud.githubusercontent.com/assets/4047597/6262188/55ded740-b824-11e4-854a-2f9353d18dba.png)

**Comment by vanwaard** [comment]
Avi

Thanks works perfect.


Met vriendelijke groet,
Fred van Waard
Verzonden vanaf Samsung-tablet


-------- Oorspronkelijk bericht --------
Van: Avi Aryan <notifications@github.com> 
Datum: 19-02-2015  06:15  (GMT+01:00) 
Aan: aviaryan/Clipjump <Clipjump@noreply.github.com> 
Cc: Fred van Waard <fred@vanwaard.nl> 
Onderwerp: Re: [Clipjump] Delete complet index of a channel (#63) 

Select a channel in Channel organizer, then select Delete and choose No option
