### ISSUE TITLE
Save clipboard to a file and copy file path to clipboard

### ISSUE THREAD

**Issue by danielo515** [aviaryan/Clipjump#66]
I just realized that one of the most repetitive task in my day to day is to copy something to the clipboard, copy the clipboard to a file and then attach it to somewhere. Since clipjump already stores the clipboard on text files it would be nice to have a shortcut to copy current clipboard content to a file and then copy that file path to the clipboar.

Would not it be lovely?

**Comment by aviaryan** [comment]
If you want this feature for yourself, then you can easily do this with the plugin system.

**Steps**
1) Use [getClipAt](http://clipjump.sourceforge.net/docs/devList.html#api) to the get the contents of currently active clipboard.
2) Then use AutoHotkey's command [FileAppend](http://www.autohotkey.com/docs/commands/FileAppend.htm) to write that to file.
3) Copy the filepath to Clipjump by assigning the clipboard variable..

Here is a pseudo-code ..

```autohotkey
clipContent = API.getClipAt(CN.NG, 1)
FileAppend, %clipContent%, %A_temp%/abcd.txt
Clipboard  = %A_temp%/abcd.txt
```
