### ISSUE TITLE
Discrepancy between plugins in clipjump an clipjump-addons

### ISSUE THREAD

**Issue by hoppfrosch** [aviaryan/Clipjump#68]
Currently there are two main repositories provided for clipjump:
* https://github.com/aviaryan/Clipjump
* https://github.com/aviaryan/clipjump-addons

The two repositories do not contain the same plugin contents ... The clipjump-addons repository was introduced recently - after the clipjump repo already holds the plugins subdirectory

* What are the reasons to separate the addons from the original clipjump repository?
* Are there plans to remove the plugins subdirectory and incorporate the clipjump-addons repository as a git submodule into the main clipjump repository? (to have the latest addons available when updatiung/pulling the clipjump repository)

**Comment by aviaryan** [comment]
The clipjump-addons repo will contain all the plugins for clipjump from all the developers. 
Good helpful (& official) plugins will then be uploaded to the main repo at time of each Clipjump version release.
