### ISSUE TITLE
Page titles in HTML files

### ISSUE THREAD

**Issue by hoppfrosch** [aviaryan/Clipjump#70]
One question concerning documentation style - I'm willing to work on it, but need some direction ....

Within the HTML-files there are inconsistent page titles: 

    <title>Clipjump : Troubleshooting</title>
    <title>Clipjump FAQ</title>' (no colon)
    <title>Shortcuts</title> (no preceeding "Clipjump" at all)

That's not a big thing - but if you compile your help into CHM, the page titles are used on display when using "*Search*" facility of CHM-file. There, the inconsistent title naming leads to an "unordered" list:
*Clipjump: Troubleshooting* is listed as first item, *Clipjump FAQ* as second and *Shortcut* at the end. This makes finding a certain page on the list difficult, since it's not sorted as users might expect.
As a user, I would expect a "correct" alphabetic sorting: *FAQ - Shortcut - Troubleshooting*

**Proposal**: Remove all leading *Clipjump* or *Clipjump :* from the HTML titles to get a correct alphabetic sorting in CHM-Search (Clipjump help should generally handle topics of Clipjump - therfore no need for the prefix ...)

**Comment by aviaryan** [comment]
I'll fix this. As you may have seen the clipjump [docs](http://clipjump.sourceforge.net/docs/organizer.html) on the website are now made in [jekyll](http://jekyllrb.com). Hence I will homogenize the titles next time I push docs to the repository.

**Comment by hoppfrosch** [comment]
Does this mean you don't want to support CHM anymore - or should be jekyll/chm supported in parallel using the identical html sources? I would prefer to have the documentation locally available as well ...

**Comment by hoppfrosch** [comment]
Does this mean you don't want to support CHM anymore - or should be jekyll/chm supported in parallel using the identical html sources? I would prefer to have the documentation locally available as well ...

**Comment by aviaryan** [comment]
NO. chm will be generated and distributed. The extra step involved in generating it will be compiling the doc source code with Jekyll. Nothing else. The "doc source code" is in HTML so anybody can contribute and send a PR. They don't need to learn a word about Jekyll.
I will put up the new docs soon. Currently I will check how the Jekyll docs look when they are made to CHM.

**Comment by aviaryan** [comment]
Fixed from https://github.com/aviaryan/Clipjump/commit/142e8af95a62d4dc43ab766f05fe3615faccd1f6 and subsequent commits. Closing
