### ISSUE TITLE
How to change pastemodekey in instructions is not clear

### ISSUE THREAD

**Issue by danielo515** [aviaryan/Clipjump#72]
In the Help document of clipjump, there is one section dedicated to changing the pastemodekeys. This sections is very helpful, but it does not explain that the usage of the control (`^`) modifier is mandatory. Since this can be obvious for you, it is not for everyone.

**Comment by aviaryan** [comment]
I agree. This will be fixed. Thanks

**Comment by aviaryan** [comment]
Fixed by https://github.com/aviaryan/Clipjump/commit/229f4db140cedbe50bfbde6a621948d6c73e72b5
