### ISSUE TITLE
Autocopy feature :)

### ISSUE THREAD

**Issue by Aabhi021290** [aviaryan/Clipjump#75]
First of all ,Thank you Developer for this amazing software.
I dont know where I should put my request, so if it wrong place then Sorry.
I use your software daily.I use is to make notes for my study purpose.
But one thing I want from this software which is explained below

Step 1: When I press some key combination it activates "AUTO COPY MODE" (AUTO COPY MODE is explained below)
Step 2: In AUTO COPY MODE, when ever I select any text, it automatically copy in clip board (without pressing Ctrl+C)
Step 3:When I press again that key combination of step 1, clipjump starts working normally.
If this Auto copy feature is already present then please guide me.

**Comment by aviaryan** [comment]
No such a feature doesn't exist but this is possible via AutoHotkey. ([Example](http://www.autohotkey.com/board/topic/5139-auto-copy-selected-text-to-clipboard/))

**Comment by Aabhi021290** [comment]
Thanks
