### ISSUE TITLE
Help files do not show

### ISSUE THREAD

**Issue by blokeley** [aviaryan/Clipjump#76]
I downloaded the latest clipjump (11.6.1) and unzipped the ZIP file.

The Clipjump.chm file opens OK and the Contents, Index and Search tabs have content, but the main window shows no help files.

Operating system: Windows 7 64-bit

**Comment by aviaryan** [comment]
See http://weblog.helpware.net/?p=36
The Unblock part.

**Comment by blokeley** [comment]
That worked. 
Having read the just the First Steps, it's obvious that Clipjump is very powerful indeed. Wonderful.
