### ISSUE TITLE
Deleting items from history does not work

### ISSUE THREAD

**Issue by blokeley** [aviaryan/Clipjump#77]
To replicate:

1. Copy some items to the clipboard (Ctrl-C)
2. Use the Action Mode (Ctrl-Shift-A) then H to access the history.
3. Select some items and press Delete to delete them.
4. Focus on a document somewhere and press Ctrl-V, V, V, V...

The deleted items are still there, and they're there if you look in the Channel Organizer (Ctrl-Shift-A; O).

**Comment by aviaryan** [comment]
From [FAQ](http://clipjump.sourceforge.net/docs/faq.html)

The Clear History button in History Tool doesn't delete the recent Clips in Ctrl+V Paste Mode ?
OR
I delete a clip from Ctrl+V Paste Mode but it is still there in History Tool ?
The History Tool and the Paste-Mode are two different components and there clips are independent of each other. 
History Tool is meant for history-keeping whereas Ctrl+V Paste Mode is meant to show clips contained in different channels of Clipjump. 
The record of all clips added to any of the channels are shown in a single window i.e. History Tool. On the other hand, clips stored in channels can be managed from the Channel Organizer.

**Comment by blokeley** [comment]
OK, I understand now. It might be worth adding a note to the History window explaining this.
