### ISSUE TITLE
Add "pop" from channel

### ISSUE THREAD

**Issue by blokeley** [aviaryan/Clipjump#78]
If a channel is a [stack](http://en.m.wikipedia.org/wiki/Stack_%28abstract_data_type%29), then Ctrl+V performs a "peek" (the item is left on the channel).

Could it be made that, if the user also holds Shift when releasing Ctrl, a "pop" is performed so that the pasted item is removed from the channel?

I often have a stack of one-off pastes to do.

**Comment by aviaryan** [comment]
This is a nice idea. I will try to implement something similar.

**Comment by aviaryan** [comment]
I just implemented it and it works the same way you suggested. Thank you for a good idea. One thing to note here is that the user should release Shift after Ctrl for this to work.
