### ISSUE TITLE
Any chance for Linux?

### ISSUE THREAD

**Issue by YitzhakStone** [aviaryan/Clipjump#86]
I tested many options on Linux, but none as ClipJump.

**Comment by aviaryan** [comment]
AutoHotkey ( the language Clipjump is made in ) is not supported on Linux so Clipjump is not supported. The only way to have Clipjump on linux is to remake it in some other language.. I currently don't have such plans

**Comment by YitzhakStone** [comment]
Sad :( 
If you know any similar tool (on linux) as good as ClipJump, give news!

**Comment by transtone** [comment]
http://parcellite.sourceforge.net/ will help you

**Comment by YitzhakStone** [comment]
I'll try modify this... :smile: thanks!

**Comment by githubuser441** [comment]
Any updates or better alternatives?
