### ISSUE TITLE
collision with emacs hot keys

### ISSUE THREAD

**Issue by transtone** [aviaryan/Clipjump#89]
If I use clipjump, my emacs hot key is changed, even added "Emacs" to ignore window.

Emacs always use C-x for prefix, Is clipjump change it?
Can I disable C-x in clipjump?
Can I set something let clipjump realy not bother Emacs?

```
nativeCut:
	Critical
	if WinActive("ahk_class XLMAIN")
	{
		hkZ("$^x", "nativeCut", 0) , hkZ("$^x", "keyblocker")
		LASTCLIP := ""
		setTimer, ctrlforCopy, 50
	}
	if ini_is_duplicate_copied
		LASTCLIP := ""
	CLIP_ACTION := "CUT"
	Send, ^{vk58}
	return
```
Is this function ignore windows in 'ignore list'?

**Comment by aviaryan** [comment]
I don't use Emacs but I installed it today and it worked well. I tried some C-x commands like C-x C-h and they worked. I didn't even had to add it to ignored windows list .

What do you mean by "emacs hotkey changed" ? Is C-x in emacs not working.

BTW, the above function (label) shouldn't really bother emacs..

**Comment by transtone** [comment]
Could u please try this one? http://sourceforge.net/projects/emacsbinw64/
