### ISSUE TITLE
Clipjump 12.3 crash

### ISSUE THREAD

**Issue by happysurf** [aviaryan/Clipjump#97]
In Windows XP SP3 + Clipjump 12.3 I get this error during copy and paste operations:

![clipjump](https://cloud.githubusercontent.com/assets/13637587/12971785/122bc000-d09f-11e5-801f-785071455daa.png)

Version 12.0 works fine.
Thanks.

**Comment by aviaryan** [comment]
Can you translate the message for me?

**Comment by happysurf** [comment]
**GDI+ Window: Clipjump.exe - Aplication Error**

The instruction at "0x4ebe74b2" referenced memory at "0x4ebe74b2". The memory could not be "read".
Click on OK to terminate the program.
Click on OK to execute the application debug.

**Comment by aviaryan** [comment]
Does it happen everytime you copy something or are there any specific cases ?
Also after the error, is the item actually copied to Clipjump (in Paste Mode Ctrl-V) ?

**Comment by aviaryan** [comment]
Can you try something, replace the Clipjump.exe of v12.3 with Clipjump.exe of v12. .. Then run v12.3 with the new exe. 
As there was no change in the code regarding the copy-paste between these versions, I suspect it was an AutoHotkey issue.

**Comment by happysurf** [comment]
I tried Clipjump.exe 12.0 inside the 12.3 folder but I get the same error with the software in idle state.

**Comment by aviaryan** [comment]
I think your case is same as issue #90 . Can't believe how I forgot that. 
The fix in that case will be to download the repo at https://github.com/aviaryan/Clipjump/tree/f725c69ba5fd0b2ba4b1b7f164f2b2612193b215 , copy Clipjump.exe (of v12.3) to it's folder and then run.

**Comment by happysurf** [comment]
This is a great news, but in the zip file here https://github.com/aviaryan/Clipjump/archive/f725c69ba5fd0b2ba4b1b7f164f2b2612193b215.zip I don't see any Clipjump.exe file.

**Comment by aviaryan** [comment]
Use Clipjump.exe of v12.3

**Comment by happysurf** [comment]
Works fine thanks.
